HOST: http://api.discoverambient.com

--- Ambient API ---

-- User --
Returns the user with the given facebook id.
400: if fbid is missing
404: if no user with fbid is found
GET /users/search?fbid=:string
< 200
< Content-Type: application/json
{
  "user" : {
    "id" : "511371ad57259eff0637a8da",
    "first" : "Patric",
    "last" : "Fornasier",
    "location" : [ 51.554093, -0.104514 ]
  }
}

Creates a new user. The newly created user.
400: if first, last or fbid is missing
409: if user with fbid exists already
POST /users?first=:string&last=:string&fbid=:string
< 200
< Content-Type: application/json
{
  "user" : {
    "id" : "511371ad57259eff0637a8da",
    "first" : "Patric",
    "last" : "Fornasier",
    "location" : [ 51.554093, -0.104514 ]
  }
}


-- Nearby/Search --
Returns a collection of (user, distance) tuples.
400: if location is missing
GET /search/nearby?location=:double,double
< 200
< Content-Type: application/json
{
  "nearby" : [ {
    "user" : {
      "id" : "511371ae57259eff0637a8dc",
      "first" : "Marc",
      "last" : "Hofer",
      "location" : [ 51.531974, -0.099392 ]
    },
    "distance" : 2003
  }, {
    "user" : {
      "id" : "511371ae57259eff0637a8db",
      "first" : "Jae",
      "last" : "Lee",
      "location" : [ 51.537731, -0.136677 ]
    },
    "distance" : 4585
  } ]
}


-- Checkins --
Creates a new checkin. Returns nothing.
400: if user_id or location is missing
POST /checkins?user_id=:string&location=:double,double
< 200
< Content-Type: application/json
