HOST: http://api.discoverambient.com

--- Ambient API ---

-- User --
Returns the user with the given facebook id.
Other: 400, 404
GET /users/search?fb=:string
< 200
< Content-Type: application/json
{
  "user" : {
    "id" : "123",
    "name" : "Stefan Fazzlar"
  }
}

Creates a new user. The newly created user.
Other; 400, 409
POST /users?fb=:string&first=:string&last=:string
< 200
< Content-Type: application/json
{
  "user" : {
    "id" : "123",
    "name" : "Stefan Fazzlar"
  }
}


-- Nearby/Search --
Returns a collection of (user, distance) tuples.
Other: 400
GET /search/nearby?location=:double,double
< 200
< Content-Type: application/json
{
  "nearby" : [ {
    "user" : {
      "name" : "Marc Hofer"
    },
    "distance" : 2003
  }, {
    "user" : {
      "name" : "Jae Lee"
    },
    "distance" : 4585
  } ]
}


-- Checkins --
Creates a new checkin. Returns nothing.
Other: 400
POST /checkins?location=:double,double
< 200
< Content-Type: application/json
