HOST: http://api.discoverambient.com

--- Ambient API ---

-- User --
Returns the user with the given facebook id.
400: if fbid is missing
404: if no user with fbid is found
GET /users/search?fbid=:string
< 200
< Content-Type: application/json
{
  "user" : {
    "id" : "511371ad57259eff0637a8da",
    "first" : "Patric",
    "last" : "Fornasier"
  }
}

Creates a new user. The newly created user.
400: if one of (first, last, fbid, picture) is missing
409: if user with fbid exists already
POST /users?first=:string&last=:string&fbid=:string&picture=:string
< 200
< Content-Type: application/json
{
  "user" : {
    "id" : "511371ad57259eff0637a8da",
    "first" : "Patric",
    "last" : "Fornasier",
    "picture" : "http://.../pat.jpg"
  }
}


-- Nearby/Search --
Returns a collection of (user, distance) tuples.
400: if location is missing
GET /search/nearby?location=:double,double
< 200
< Content-Type: application/json
{
  "nearby" : [ {
    "user" : {
      "id" : "511371ae57259eff0637a8dc",
      "first" : "Marc",
      "last" : "Hofer"
    },
    "distance" : 2003
  }, {
    "user" : {
      "id" : "511371ae57259eff0637a8db",
      "first" : "Jae",
      "last" : "Lee"
    },
    "distance" : 4585
  } ]
}


-- Checkins --
Creates a new checkin. Returns nothing.
400: if user_id or location is missing
POST /checkins?userId=:string&location=:double,double
< 200
< Content-Type: application/json
